kind : Deployment 
apiVersion: apps/v1
metadata: 
  name: nginx-deployment
  namespace : nginx
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name : nginx-dep-tempelate
      labels:
        app: nginx

    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80  
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /var/www/html
            name: my-volume
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: local-pvc
