kind: Pod
apiVersion: v1
metadata:
  name: sidecar-test

spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  containers:
  - name: main-container
    image: busybox
    command: ["sh","-c", "while true; do echo 'Hell all' >> /var/log/app.log ; sleep 5 ; done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
  - name: sidecar-container
    image: busybox
    command: ["sh", "-c" , "tail -f   /var/log/app.log"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/
