# Vagrantfile

Vagrant.configure("2") do |config|
  # Define the base box (Ubuntu 20.04 in this case)
  #config.ssh.private_key_path = File.expand_path('~/.ssh/id_rsa')
  config.vm.box = "bento/ubuntu-22.04"
  #config.ssh.private_key_path = ~/.ssh/id_rsa
  config.ssh.forward_agent = true
  ssh_pub_key = File.readlines("/home/sanjay7178/.ssh/id_rsa.pub").first.strip
  #config.vm.synced_folder "../../kubeadm-scripts", "~/", disabled: true
  config.vm.provision "shell", inline: <<-SHELL
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
    sudo apt-get update -y
    #echo git clone https://github.com/techiescamp/kubeadm-scripts
    #echo sudo bash "~/kubeadm-scripts/common.sh"
    echo "192.168.56.10  master-node" >> /etc/hosts
    echo "192.168.56.11  worker-node01" >> /etc/hosts
    echo "192.168.56.12  worker-node02" >> /etc/hosts
    echo "VM provisioned successfully."
  SHELL



  # Create three VMs with specific IP addresses
  config.vm.define "master" do |node|
    node.vm.hostname = "master-node"
    node.vm.network "private_network", type: "dhcp"
    node.vm.network "private_network", type: "static", ip: "192.168.56.10"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "4048" # Set memory size for each VM
      vb.cpus = 2        # Set CPU count for each VM
    end
  end

  (1..2).each do |i|
  config.vm.define "node0#{i}" do |node|
    node.vm.hostname = "worker-node0#{i}"
    node.vm.network "private_network", type: "dhcp"
    node.vm.network "private_network", type: "static", ip: "192.168.56.1#{i}"
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
  end


  # Use a shell script to provision the VMs
  # config.vm.provision "shell", path: "provision.sh"

  end
end
